#!/usr/bin/env bash
# Rewrite bazel/versions.bzl with the sha256 of the released native binaries.
#
# This stays shell because its inputs are not Bazel artifacts: the binaries are
# built by GraalVM in the release matrix and arrive as CI artifacts, so no build
# rule can hash them. Packaging IS Bazel's job — see //:module_archive.
#
# Usage: bazel run //bazel/tools:pin_versions -- <version> <dir-with-binaries>
set -euo pipefail

: "${BUILD_WORKSPACE_DIRECTORY:?must be run via bazel run, not directly}"
cd "$BUILD_WORKSPACE_DIRECTORY"
VERSION="${1:?version, without the leading v}"
DIST="${2:?directory holding the built binaries}"
DIST="$(cd "$DIST" && pwd)"

platforms=(linux_x86_64 linux_aarch64 darwin_x86_64 darwin_arm64)

{
  echo '"""Checksums for the released native binaries, keyed by Bazel platform.'
  echo
  echo "GENERATED by //bazel/tools:pin_versions for v$VERSION. Do not edit by hand: the"
  echo 'copy in git is intentionally empty, because these hashes only exist once'
  echo 'the release binaries have been built.'
  echo '"""'
  echo
  echo "VERSION = \"$VERSION\""
  echo
  echo '# "os_arch": (sha256, asset name)'
  echo "BINARIES = {"
  for p in "${platforms[@]}"; do
    asset="protoc-gen-clojure_${VERSION}_${p}"
    path="$DIST/$asset"
    [ -f "$path" ] || {
      echo "missing binary for $p at $path" >&2
      exit 1
    }
    echo "    \"$p\": (\"$(sha256sum "$path" | cut -d' ' -f1)\", \"$asset\"),"
  done
  echo "}"
  echo
  echo "# Bazel constraint values per key above."
  echo "PLATFORMS = {"
  echo '    "linux_x86_64": ["@platforms//os:linux", "@platforms//cpu:x86_64"],'
  echo '    "linux_aarch64": ["@platforms//os:linux", "@platforms//cpu:aarch64"],'
  echo '    "darwin_x86_64": ["@platforms//os:macos", "@platforms//cpu:x86_64"],'
  echo '    "darwin_arm64": ["@platforms//os:macos", "@platforms//cpu:arm64"],'
  echo "}"
} >bazel/versions.bzl

echo "pinned ${#platforms[@]} binaries for v$VERSION in bazel/versions.bzl"
