;; Generated by protoc-gen-clojure from fixtures/nested/nested.proto. Do not edit.
;;
;; The FileDescriptorProto below is embedded verbatim; protobuf-java resolves
;; its edition features at load time, so this file needs no regeneration when
;; a new edition ships.
(ns fixtures.nested.nested
  (:require [clj-grpc.codec :as codec]
            [clj-grpc.runtime :as rt]))

(def ^:private descriptor-b64
  "ChxmaXh0dXJlcy9uZXN0ZWQvbmVzdGVkLnByb3RvEg9maXh0dXJlcy5uZXN0ZWQixgMKBU91dGVyEg4KAmlkGAEgASgJUgJpZBI6CgZjb3VudHMYAiADKAsyIi5maXh0dXJlcy5uZXN0ZWQuT3V0ZXIuQ291bnRzRW50cnlSBmNvdW50cxIyCgVpbm5lchgDIAEoCzIcLmZpeHR1cmVzLm5lc3RlZC5PdXRlci5Jbm5lclIFaW5uZXIaOQoLQ291bnRzRW50cnkSEAoDa2V5GAEgASgJUgNrZXkSFAoFdmFsdWUYAiABKAVSBXZhbHVlOgI4ARqBAgoFSW5uZXISEgoEbmFtZRgBIAEoCVIEbmFtZRJACgZsYWJlbHMYAiADKAsyKC5maXh0dXJlcy5uZXN0ZWQuT3V0ZXIuSW5uZXIuTGFiZWxzRW50cnlSBmxhYmVscxJECglpbm5lcm1vc3QYAyABKAsyJi5maXh0dXJlcy5uZXN0ZWQuT3V0ZXIuSW5uZXIuSW5uZXJtb3N0Uglpbm5lcm1vc3QaOQoLTGFiZWxzRW50cnkSEAoDa2V5GAEgASgJUgNrZXkSFAoFdmFsdWUYAiABKAlSBXZhbHVlOgI4ARohCglJbm5lcm1vc3QSFAoFZGVwdGgYASABKAVSBWRlcHRoIiUKBUlubmVyEhwKCXVucmVsYXRlZBgBIAEoCVIJdW5yZWxhdGVkQhwKGGNvbS5hY21lLmZpeHR1cmVzLm5lc3RlZFABYgZwcm90bzM=")

(def file-descriptor
  (rt/file-descriptor descriptor-b64
                      []))

;; ---------------------------------------------------------------
;; messages
;;
;; The shape is known at codegen time, so the representation is too:
;; a defrecord per type, its FieldDescriptors resolved once into
;; vars, and straight-line ->proto/proto-> built on them. nil means
;; absent, which is how a record (all keys always present) maps onto
;; protobuf explicit presence.

(defrecord Outer [id counts inner])
(def Outer-prototype (rt/message file-descriptor "Outer" "com.acme.fixtures.nested.Outer"))
(def ^:private Outer--id (rt/field Outer-prototype "id"))
(def ^:private Outer--counts (rt/field Outer-prototype "counts"))
(def ^:private Outer--inner (rt/field Outer-prototype "inner"))
(defn Outer->proto
  "Clojure -> protobuf. Takes the Outer record or any map
  with the same keys — records and plain maps are interchangeable."
  ([m] (Outer->proto m nil))
  ([m opts]
   (let [b (.newBuilderForType ^com.google.protobuf.Message Outer-prototype)]
     (codec/set-field! b Outer--id (:id m) opts)
     (codec/set-field! b Outer--counts (:counts m) opts)
     (codec/set-field! b Outer--inner (:inner m) opts)
     (.build b))))
(defn proto->Outer
  "protobuf -> a Outer record. Absent fields are nil."
  ([msg] (proto->Outer msg nil))
  ([^com.google.protobuf.Message msg opts]
   (->Outer
    (codec/get-field msg Outer--id opts)
    (codec/get-field msg Outer--counts opts)
    (codec/get-field msg Outer--inner opts)
    )))

(defrecord Outer-Inner [name labels innermost])
(def Outer-Inner-prototype (rt/message file-descriptor "Outer.Inner" "com.acme.fixtures.nested.Outer$Inner"))
(def ^:private Outer-Inner--name (rt/field Outer-Inner-prototype "name"))
(def ^:private Outer-Inner--labels (rt/field Outer-Inner-prototype "labels"))
(def ^:private Outer-Inner--innermost (rt/field Outer-Inner-prototype "innermost"))
(defn Outer-Inner->proto
  "Clojure -> protobuf. Takes the Outer-Inner record or any map
  with the same keys — records and plain maps are interchangeable."
  ([m] (Outer-Inner->proto m nil))
  ([m opts]
   (let [b (.newBuilderForType ^com.google.protobuf.Message Outer-Inner-prototype)]
     (codec/set-field! b Outer-Inner--name (:name m) opts)
     (codec/set-field! b Outer-Inner--labels (:labels m) opts)
     (codec/set-field! b Outer-Inner--innermost (:innermost m) opts)
     (.build b))))
(defn proto->Outer-Inner
  "protobuf -> a Outer-Inner record. Absent fields are nil."
  ([msg] (proto->Outer-Inner msg nil))
  ([^com.google.protobuf.Message msg opts]
   (->Outer-Inner
    (codec/get-field msg Outer-Inner--name opts)
    (codec/get-field msg Outer-Inner--labels opts)
    (codec/get-field msg Outer-Inner--innermost opts)
    )))

(defrecord Outer-Inner-Innermost [depth])
(def Outer-Inner-Innermost-prototype (rt/message file-descriptor "Outer.Inner.Innermost" "com.acme.fixtures.nested.Outer$Inner$Innermost"))
(def ^:private Outer-Inner-Innermost--depth (rt/field Outer-Inner-Innermost-prototype "depth"))
(defn Outer-Inner-Innermost->proto
  "Clojure -> protobuf. Takes the Outer-Inner-Innermost record or any map
  with the same keys — records and plain maps are interchangeable."
  ([m] (Outer-Inner-Innermost->proto m nil))
  ([m opts]
   (let [b (.newBuilderForType ^com.google.protobuf.Message Outer-Inner-Innermost-prototype)]
     (codec/set-field! b Outer-Inner-Innermost--depth (:depth m) opts)
     (.build b))))
(defn proto->Outer-Inner-Innermost
  "protobuf -> a Outer-Inner-Innermost record. Absent fields are nil."
  ([msg] (proto->Outer-Inner-Innermost msg nil))
  ([^com.google.protobuf.Message msg opts]
   (->Outer-Inner-Innermost
    (codec/get-field msg Outer-Inner-Innermost--depth opts)
    )))

(defrecord Inner [unrelated])
(def Inner-prototype (rt/message file-descriptor "Inner" "com.acme.fixtures.nested.Inner"))
(def ^:private Inner--unrelated (rt/field Inner-prototype "unrelated"))
(defn Inner->proto
  "Clojure -> protobuf. Takes the Inner record or any map
  with the same keys — records and plain maps are interchangeable."
  ([m] (Inner->proto m nil))
  ([m opts]
   (let [b (.newBuilderForType ^com.google.protobuf.Message Inner-prototype)]
     (codec/set-field! b Inner--unrelated (:unrelated m) opts)
     (.build b))))
(defn proto->Inner
  "protobuf -> a Inner record. Absent fields are nil."
  ([msg] (proto->Inner msg nil))
  ([^com.google.protobuf.Message msg opts]
   (->Inner
    (codec/get-field msg Inner--unrelated opts)
    )))
