;; Generated by protoc-gen-clojure from acme/greeter/greeter.proto. Do not edit.
;;
;; The FileDescriptorProto below is embedded verbatim; protobuf-java resolves
;; its edition features at load time, so this file needs no regeneration when
;; a new edition ships.
(ns acme.greeter.greeter
  (:require [clj-grpc.codec :as codec]
            [clj-grpc.runtime :as rt]
            [clj-grpc.runtime.service :as rts]))

(def ^:private descriptor-b64
  "ChphY21lL2dyZWV0ZXIvZ3JlZXRlci5wcm90bxIMYWNtZS5ncmVldGVyInkKDEhlbGxvUmVxdWVzdBISCgRuYW1lGAEgASgJUgRuYW1lEiEKDHJlcGVhdF9jb3VudBgCIAEoBVILcmVwZWF0Q291bnQSMgoIZ3JlZXRpbmcYAyABKA4yFi5hY21lLmdyZWV0ZXIuR3JlZXRpbmdSCGdyZWV0aW5nIiYKCkhlbGxvUmVwbHkSGAoHbWVzc2FnZRgBIAEoCVIHbWVzc2FnZSpMCghHcmVldGluZxIYChRHUkVFVElOR19VTlNQRUNJRklFRBAAEhIKDkdSRUVUSU5HX0hFTExPEAESEgoOR1JFRVRJTkdfSE9XRFkQAjKeAgoHR3JlZXRlchJACghTYXlIZWxsbxIaLmFjbWUuZ3JlZXRlci5IZWxsb1JlcXVlc3QaGC5hY21lLmdyZWV0ZXIuSGVsbG9SZXBseRJGCgxTYXlIZWxsb01hbnkSGi5hY21lLmdyZWV0ZXIuSGVsbG9SZXF1ZXN0GhguYWNtZS5ncmVldGVyLkhlbGxvUmVwbHkwARJHCg1Db2xsZWN0SGVsbG9zEhouYWNtZS5ncmVldGVyLkhlbGxvUmVxdWVzdBoYLmFjbWUuZ3JlZXRlci5IZWxsb1JlcGx5KAESQAoEQ2hhdBIaLmFjbWUuZ3JlZXRlci5IZWxsb1JlcXVlc3QaGC5hY21lLmdyZWV0ZXIuSGVsbG9SZXBseSgBMAFCEgoQY29tLmFjbWUuZ3JlZXRlcmIIZWRpdGlvbnNw6Qc=")

(def file-descriptor
  (rt/file-descriptor descriptor-b64
                      []))

;; ---------------------------------------------------------------
;; messages
;;
;; The shape is known at codegen time, so the representation is too:
;; a defrecord per type, its FieldDescriptors resolved once into
;; vars, and straight-line ->proto/proto-> built on them. nil means
;; absent, which is how a record (all keys always present) maps onto
;; protobuf explicit presence.

(defrecord HelloRequest [name repeat-count greeting])
(def HelloRequest-prototype (rt/message file-descriptor "HelloRequest" "com.acme.greeter.HelloRequest"))
(def ^:private HelloRequest--name (rt/field HelloRequest-prototype "name"))
(def ^:private HelloRequest--repeat-count (rt/field HelloRequest-prototype "repeat_count"))
(def ^:private HelloRequest--greeting (rt/field HelloRequest-prototype "greeting"))
(defn HelloRequest->proto
  "Clojure -> protobuf. Takes the HelloRequest record or any map
  with the same keys — records and plain maps are interchangeable."
  ([m] (HelloRequest->proto m nil))
  ([m opts]
   (let [b (.newBuilderForType ^com.google.protobuf.Message HelloRequest-prototype)]
     (codec/set-field! b HelloRequest--name (:name m) opts)
     (codec/set-field! b HelloRequest--repeat-count (:repeat-count m) opts)
     (codec/set-field! b HelloRequest--greeting (:greeting m) opts)
     (.build b))))
(defn proto->HelloRequest
  "protobuf -> a HelloRequest record. Absent fields are nil."
  ([msg] (proto->HelloRequest msg nil))
  ([^com.google.protobuf.Message msg opts]
   (->HelloRequest
    (codec/get-field msg HelloRequest--name opts)
    (codec/get-field msg HelloRequest--repeat-count opts)
    (codec/get-field msg HelloRequest--greeting opts)
    )))

(defrecord HelloReply [message])
(def HelloReply-prototype (rt/message file-descriptor "HelloReply" "com.acme.greeter.HelloReply"))
(def ^:private HelloReply--message (rt/field HelloReply-prototype "message"))
(defn HelloReply->proto
  "Clojure -> protobuf. Takes the HelloReply record or any map
  with the same keys — records and plain maps are interchangeable."
  ([m] (HelloReply->proto m nil))
  ([m opts]
   (let [b (.newBuilderForType ^com.google.protobuf.Message HelloReply-prototype)]
     (codec/set-field! b HelloReply--message (:message m) opts)
     (.build b))))
(defn proto->HelloReply
  "protobuf -> a HelloReply record. Absent fields are nil."
  ([msg] (proto->HelloReply msg nil))
  ([^com.google.protobuf.Message msg opts]
   (->HelloReply
    (codec/get-field msg HelloReply--message opts)
    )))

;; services — pass the service value to your server, the methods to a client
(def Greeter (rts/service file-descriptor "Greeter"))
(def greeter-methods (rts/methods-map Greeter))
