;; Generated by protoc-gen-clojure from fixtures/nested/nested.proto. Do not edit.
;;
;; The FileDescriptorProto below is embedded verbatim; protobuf-java resolves
;; its edition features at load time, so this file needs no regeneration when
;; a new edition ships.
(ns fixtures.nested.nested
  (:require [clj-protobuf.codec :as codec]
            [clj-protobuf.runtime :as rt]))

(def ^:private descriptor-b64
  "ChxmaXh0dXJlcy9uZXN0ZWQvbmVzdGVkLnByb3RvEg9maXh0dXJlcy5uZXN0ZWQixgMKBU91dGVyEg4KAmlkGAEgASgJUgJpZBI6CgZjb3VudHMYAiADKAsyIi5maXh0dXJlcy5uZXN0ZWQuT3V0ZXIuQ291bnRzRW50cnlSBmNvdW50cxIyCgVpbm5lchgDIAEoCzIcLmZpeHR1cmVzLm5lc3RlZC5PdXRlci5Jbm5lclIFaW5uZXIaOQoLQ291bnRzRW50cnkSEAoDa2V5GAEgASgJUgNrZXkSFAoFdmFsdWUYAiABKAVSBXZhbHVlOgI4ARqBAgoFSW5uZXISEgoEbmFtZRgBIAEoCVIEbmFtZRJACgZsYWJlbHMYAiADKAsyKC5maXh0dXJlcy5uZXN0ZWQuT3V0ZXIuSW5uZXIuTGFiZWxzRW50cnlSBmxhYmVscxJECglpbm5lcm1vc3QYAyABKAsyJi5maXh0dXJlcy5uZXN0ZWQuT3V0ZXIuSW5uZXIuSW5uZXJtb3N0Uglpbm5lcm1vc3QaOQoLTGFiZWxzRW50cnkSEAoDa2V5GAEgASgJUgNrZXkSFAoFdmFsdWUYAiABKAlSBXZhbHVlOgI4ARohCglJbm5lcm1vc3QSFAoFZGVwdGgYASABKAVSBWRlcHRoIiUKBUlubmVyEhwKCXVucmVsYXRlZBgBIAEoCVIJdW5yZWxhdGVkQhwKGGNvbS5hY21lLmZpeHR1cmVzLm5lc3RlZFABYgZwcm90bzM=")

(def file-descriptor
  (rt/file-descriptor descriptor-b64
                      []))

;; ---------------------------------------------------------------
;; messages
(declare Outer->proto Outer-Inner->proto Outer-Inner-Innermost->proto Inner->proto proto->Outer-Inner--map proto->Outer-Inner-Innermost--map proto->Outer-Inner--slot-map proto->Outer-Inner-Innermost--slot-map)
;;
;; The shape is known at codegen time, so the representation is too:
;; a defrecord per type, its FieldDescriptors resolved once into
;; vars, and straight-line ->proto/proto-> built on them. nil means
;; absent, which is how a record (all keys always present) maps onto
;; protobuf explicit presence.

(defrecord Outer [id counts inner])
(def Outer-prototype (rt/message file-descriptor "Outer" "com.acme.fixtures.nested.Outer"))
(def ^:private Outer--id (rt/field Outer-prototype "id"))
(def ^:private Outer--counts (rt/field Outer-prototype "counts"))
(def ^:private Outer--inner (rt/field Outer-prototype "inner"))
(defn Outer->proto
  "Clojure -> protobuf. Takes the Outer record or any map
  with the same keys — records and plain maps are interchangeable."
  ([m] (Outer->proto m nil))
  ([m opts]
   (if (nil? opts)
     (let [b (com.acme.fixtures.nested.Outer/newBuilder)]
       (when-some [v (:id m)] (.setId b ^String v))
       (codec/set-field! b Outer--counts (:counts m) nil)
       (when-some [v (:inner m)] (if (map? v) (.setInner b ^com.acme.fixtures.nested.Outer$Inner (Outer-Inner->proto v nil)) (codec/set-field! b Outer--inner v nil)))
       (.build b))
     (let [b (.newBuilderForType ^com.google.protobuf.Message Outer-prototype)]
       (codec/set-field! b Outer--id (:id m) opts)
       (codec/set-field! b Outer--counts (:counts m) opts)
       (codec/set-field! b Outer--inner (:inner m) opts)
       (.build b)))))
(defn proto->Outer
  "protobuf -> a Outer record. Absent fields are nil."
  ([msg] (proto->Outer msg nil))
  ([^com.google.protobuf.Message msg opts]
   (cond
     (and (nil? opts) (instance? com.acme.fixtures.nested.Outer msg))
     (let [^com.acme.fixtures.nested.Outer m msg]
       (->Outer
        (.getId m)
        (let [jm (.getCountsMap m)] (when-not (.isEmpty jm) (persistent! (reduce (fn [acc ^java.util.Map$Entry e] (assoc! acc (.getKey e) (.getValue e))) (transient {}) (.entrySet jm)))))
        (when (.hasInner m) (proto->Outer-Inner--map (.getInner m)))
        ))

     (and (nil? opts) (rt/compiled-message? msg))
     (->Outer
      (let [v (rt/slot msg 0)] (if (nil? v) "" v))
      (let [^java.util.Map jm (rt/slot msg 1)] (when (and jm (pos? (.size jm))) (persistent! (reduce (fn [acc ^java.util.Map$Entry e] (assoc! acc (.getKey e) (.getValue e))) (transient {}) (.entrySet jm)))))
      (when-some [v (rt/slot msg 2)] (proto->Outer-Inner--slot-map v))
      )

     :else
     (->Outer
      (codec/get-field msg Outer--id opts)
      (codec/get-field msg Outer--counts opts)
      (codec/get-field msg Outer--inner opts)
      ))))

(defrecord Outer-Inner [name labels innermost])
(def Outer-Inner-prototype (rt/message file-descriptor "Outer.Inner" "com.acme.fixtures.nested.Outer$Inner"))
(def ^:private Outer-Inner--name (rt/field Outer-Inner-prototype "name"))
(def ^:private Outer-Inner--labels (rt/field Outer-Inner-prototype "labels"))
(def ^:private Outer-Inner--innermost (rt/field Outer-Inner-prototype "innermost"))
(defn Outer-Inner->proto
  "Clojure -> protobuf. Takes the Outer-Inner record or any map
  with the same keys — records and plain maps are interchangeable."
  ([m] (Outer-Inner->proto m nil))
  ([m opts]
   (if (nil? opts)
     (let [b (com.acme.fixtures.nested.Outer$Inner/newBuilder)]
       (when-some [v (:name m)] (.setName b ^String v))
       (codec/set-field! b Outer-Inner--labels (:labels m) nil)
       (when-some [v (:innermost m)] (if (map? v) (.setInnermost b ^com.acme.fixtures.nested.Outer$Inner$Innermost (Outer-Inner-Innermost->proto v nil)) (codec/set-field! b Outer-Inner--innermost v nil)))
       (.build b))
     (let [b (.newBuilderForType ^com.google.protobuf.Message Outer-Inner-prototype)]
       (codec/set-field! b Outer-Inner--name (:name m) opts)
       (codec/set-field! b Outer-Inner--labels (:labels m) opts)
       (codec/set-field! b Outer-Inner--innermost (:innermost m) opts)
       (.build b)))))
(defn proto->Outer-Inner
  "protobuf -> a Outer-Inner record. Absent fields are nil."
  ([msg] (proto->Outer-Inner msg nil))
  ([^com.google.protobuf.Message msg opts]
   (cond
     (and (nil? opts) (instance? com.acme.fixtures.nested.Outer$Inner msg))
     (let [^com.acme.fixtures.nested.Outer$Inner m msg]
       (->Outer-Inner
        (.getName m)
        (let [jm (.getLabelsMap m)] (when-not (.isEmpty jm) (persistent! (reduce (fn [acc ^java.util.Map$Entry e] (assoc! acc (.getKey e) (.getValue e))) (transient {}) (.entrySet jm)))))
        (when (.hasInnermost m) (proto->Outer-Inner-Innermost--map (.getInnermost m)))
        ))

     (and (nil? opts) (rt/compiled-message? msg))
     (->Outer-Inner
      (let [v (rt/slot msg 0)] (if (nil? v) "" v))
      (let [^java.util.Map jm (rt/slot msg 1)] (when (and jm (pos? (.size jm))) (persistent! (reduce (fn [acc ^java.util.Map$Entry e] (assoc! acc (.getKey e) (.getValue e))) (transient {}) (.entrySet jm)))))
      (when-some [v (rt/slot msg 2)] (proto->Outer-Inner-Innermost--slot-map v))
      )

     :else
     (->Outer-Inner
      (codec/get-field msg Outer-Inner--name opts)
      (codec/get-field msg Outer-Inner--labels opts)
      (codec/get-field msg Outer-Inner--innermost opts)
      ))))
(defn- proto->Outer-Inner--map
  "Outer-Inner as the plain map a nested field reads back as:
  the same values, minus the keys the codec's read leaves out."
  [^com.acme.fixtures.nested.Outer$Inner m]
  (let [labels--v (let [jm (.getLabelsMap m)] (when-not (.isEmpty jm) (persistent! (reduce (fn [acc ^java.util.Map$Entry e] (assoc! acc (.getKey e) (.getValue e))) (transient {}) (.entrySet jm)))))
        innermost--v (when (.hasInnermost m) (proto->Outer-Inner-Innermost--map (.getInnermost m)))]
    (if (and (some? labels--v) (some? innermost--v))
      {:name (.getName m)
       :labels labels--v
       :innermost innermost--v}
      (persistent!
       (cond-> (transient {:name (.getName m)})
         (some? labels--v) (assoc! :labels labels--v)
         (some? innermost--v) (assoc! :innermost innermost--v)
         )))))
(defn- proto->Outer-Inner--slot-map
  "Outer-Inner as a plain map, read from the compiled arm's slots:
  the same values, minus the keys the codec's read leaves out."
  [msg]
  (let [labels--v (let [^java.util.Map jm (rt/slot msg 1)] (when (and jm (pos? (.size jm))) (persistent! (reduce (fn [acc ^java.util.Map$Entry e] (assoc! acc (.getKey e) (.getValue e))) (transient {}) (.entrySet jm)))))
        innermost--v (when-some [v (rt/slot msg 2)] (proto->Outer-Inner-Innermost--slot-map v))]
    (if (and (some? labels--v) (some? innermost--v))
      {:name (let [v (rt/slot msg 0)] (if (nil? v) "" v))
       :labels labels--v
       :innermost innermost--v}
      (persistent!
       (cond-> (transient {:name (let [v (rt/slot msg 0)] (if (nil? v) "" v))})
         (some? labels--v) (assoc! :labels labels--v)
         (some? innermost--v) (assoc! :innermost innermost--v)
         )))))

(defrecord Outer-Inner-Innermost [depth])
(def Outer-Inner-Innermost-prototype (rt/message file-descriptor "Outer.Inner.Innermost" "com.acme.fixtures.nested.Outer$Inner$Innermost"))
(def ^:private Outer-Inner-Innermost--depth (rt/field Outer-Inner-Innermost-prototype "depth"))
(defn Outer-Inner-Innermost->proto
  "Clojure -> protobuf. Takes the Outer-Inner-Innermost record or any map
  with the same keys — records and plain maps are interchangeable."
  ([m] (Outer-Inner-Innermost->proto m nil))
  ([m opts]
   (if (nil? opts)
     (let [b (com.acme.fixtures.nested.Outer$Inner$Innermost/newBuilder)]
       (when-some [v (:depth m)] (.setDepth b (int v)))
       (.build b))
     (let [b (.newBuilderForType ^com.google.protobuf.Message Outer-Inner-Innermost-prototype)]
       (codec/set-field! b Outer-Inner-Innermost--depth (:depth m) opts)
       (.build b)))))
(defn proto->Outer-Inner-Innermost
  "protobuf -> a Outer-Inner-Innermost record. Absent fields are nil."
  ([msg] (proto->Outer-Inner-Innermost msg nil))
  ([^com.google.protobuf.Message msg opts]
   (cond
     (and (nil? opts) (instance? com.acme.fixtures.nested.Outer$Inner$Innermost msg))
     (let [^com.acme.fixtures.nested.Outer$Inner$Innermost m msg]
       (->Outer-Inner-Innermost
        (.getDepth m)
        ))

     (and (nil? opts) (rt/compiled-message? msg))
     (->Outer-Inner-Innermost
      (let [v (rt/slot msg 0)] (if (nil? v) (int 0) v))
      )

     :else
     (->Outer-Inner-Innermost
      (codec/get-field msg Outer-Inner-Innermost--depth opts)
      ))))
(defn- proto->Outer-Inner-Innermost--map
  "Outer-Inner-Innermost as the plain map a nested field reads back as:
  the same values, minus the keys the codec's read leaves out."
  [^com.acme.fixtures.nested.Outer$Inner$Innermost m]
  {:depth (.getDepth m)})
(defn- proto->Outer-Inner-Innermost--slot-map
  "Outer-Inner-Innermost as a plain map, read from the compiled arm's slots:
  the same values, minus the keys the codec's read leaves out."
  [msg]
  {:depth (let [v (rt/slot msg 0)] (if (nil? v) (int 0) v))})

(defrecord Inner [unrelated])
(def Inner-prototype (rt/message file-descriptor "Inner" "com.acme.fixtures.nested.Inner"))
(def ^:private Inner--unrelated (rt/field Inner-prototype "unrelated"))
(defn Inner->proto
  "Clojure -> protobuf. Takes the Inner record or any map
  with the same keys — records and plain maps are interchangeable."
  ([m] (Inner->proto m nil))
  ([m opts]
   (if (nil? opts)
     (let [b (com.acme.fixtures.nested.Inner/newBuilder)]
       (when-some [v (:unrelated m)] (.setUnrelated b ^String v))
       (.build b))
     (let [b (.newBuilderForType ^com.google.protobuf.Message Inner-prototype)]
       (codec/set-field! b Inner--unrelated (:unrelated m) opts)
       (.build b)))))
(defn proto->Inner
  "protobuf -> a Inner record. Absent fields are nil."
  ([msg] (proto->Inner msg nil))
  ([^com.google.protobuf.Message msg opts]
   (cond
     (and (nil? opts) (instance? com.acme.fixtures.nested.Inner msg))
     (let [^com.acme.fixtures.nested.Inner m msg]
       (->Inner
        (.getUnrelated m)
        ))

     (and (nil? opts) (rt/compiled-message? msg))
     (->Inner
      (let [v (rt/slot msg 0)] (if (nil? v) "" v))
      )

     :else
     (->Inner
      (codec/get-field msg Inner--unrelated opts)
      ))))
