;; Generated by protoc-gen-clojure from fixtures/e2024legacy/legacy_style.proto. Do not edit.
;;
;; The FileDescriptorProto below is embedded verbatim; protobuf-java resolves
;; its edition features at load time, so this file needs no regeneration when
;; a new edition ships.
(ns fixtures.e2024legacy.legacy-style
  (:require [clj-grpc.codec :as codec]
            [clj-grpc.runtime :as rt]))

(def ^:private descriptor-b64
  "CidmaXh0dXJlcy9lMjAyNGxlZ2FjeS9sZWdhY3lfc3R5bGUucHJvdG8SFGZpeHR1cmVzLmUyMDI0bGVnYWN5Ir0BChJsZWdhY3lTdHlsZU1lc3NhZ2USJgoOY2FtZWxDYXNlRmllbGQYASABKAlSDmNhbWVsQ2FzZUZpZWxkEioKEVVQUEVSX1NOQUtFX0ZJRUxEGAIgASgJUg9VUFBFUlNOQUtFRklFTEQSIwoNYWxyZWFkeV9zbmFrZRgDIAEoCVIMYWxyZWFkeVNuYWtlEgwKAXgYBCABKAlSAXgSIAoLaHR0cDJTZXJ2ZXIYBSABKAlSC2h0dHAyU2VydmVyQiIKHWNvbS5hY21lLmZpeHR1cmVzLmUyMDI0bGVnYWN5kgMAYghlZGl0aW9uc3DpBw==")

(def file-descriptor
  (rt/file-descriptor descriptor-b64
                      []))

;; ---------------------------------------------------------------
;; messages
;;
;; The shape is known at codegen time, so the representation is too:
;; a defrecord per type, its FieldDescriptors resolved once into
;; vars, and straight-line ->proto/proto-> built on them. nil means
;; absent, which is how a record (all keys always present) maps onto
;; protobuf explicit presence.

(defrecord legacyStyleMessage [camel-case-field upper-snake-field already-snake x http2-server])
(def legacyStyleMessage-prototype (rt/message file-descriptor "legacyStyleMessage" "com.acme.fixtures.e2024legacy.legacyStyleMessage"))
(def ^:private legacyStyleMessage--camel-case-field (rt/field legacyStyleMessage-prototype "camelCaseField"))
(def ^:private legacyStyleMessage--upper-snake-field (rt/field legacyStyleMessage-prototype "UPPER_SNAKE_FIELD"))
(def ^:private legacyStyleMessage--already-snake (rt/field legacyStyleMessage-prototype "already_snake"))
(def ^:private legacyStyleMessage--x (rt/field legacyStyleMessage-prototype "x"))
(def ^:private legacyStyleMessage--http2-server (rt/field legacyStyleMessage-prototype "http2Server"))
(defn legacyStyleMessage->proto
  "Clojure -> protobuf. Takes the legacyStyleMessage record or any map
  with the same keys — records and plain maps are interchangeable."
  ([m] (legacyStyleMessage->proto m nil))
  ([m opts]
   (let [b (.newBuilderForType ^com.google.protobuf.Message legacyStyleMessage-prototype)]
     (codec/set-field! b legacyStyleMessage--camel-case-field (:camel-case-field m) opts)
     (codec/set-field! b legacyStyleMessage--upper-snake-field (:upper-snake-field m) opts)
     (codec/set-field! b legacyStyleMessage--already-snake (:already-snake m) opts)
     (codec/set-field! b legacyStyleMessage--x (:x m) opts)
     (codec/set-field! b legacyStyleMessage--http2-server (:http2-server m) opts)
     (.build b))))
(defn proto->legacyStyleMessage
  "protobuf -> a legacyStyleMessage record. Absent fields are nil."
  ([msg] (proto->legacyStyleMessage msg nil))
  ([^com.google.protobuf.Message msg opts]
   (->legacyStyleMessage
    (codec/get-field msg legacyStyleMessage--camel-case-field opts)
    (codec/get-field msg legacyStyleMessage--upper-snake-field opts)
    (codec/get-field msg legacyStyleMessage--already-snake opts)
    (codec/get-field msg legacyStyleMessage--x opts)
    (codec/get-field msg legacyStyleMessage--http2-server opts)
    )))
