;; Generated by protoc-gen-clojure from fixtures/e2023/kitchen.proto. Do not edit.
;;
;; The FileDescriptorProto below is embedded verbatim; protobuf-java resolves
;; its edition features at load time, so this file needs no regeneration when
;; a new edition ships.
(ns fixtures.e2023.kitchen
  (:require [clj-protobuf.codec :as codec]
            [clj-protobuf.runtime :as rt]))

(def ^:private descriptor-b64
  "ChxmaXh0dXJlcy9lMjAyMy9raXRjaGVuLnByb3RvEg5maXh0dXJlcy5lMjAyMxoeZ29vZ2xlL3Byb3RvYnVmL2R1cmF0aW9uLnByb3RvGh9nb29nbGUvcHJvdG9idWYvdGltZXN0YW1wLnByb3RvGh5nb29nbGUvcHJvdG9idWYvd3JhcHBlcnMucHJvdG8iGAoGTmVzdGVkEg4KAmlkGAEgASgJUgJpZCLuBgoHS2l0Y2hlbhIbCglzdHJfZmllbGQYASABKAlSCHN0ckZpZWxkEhsKCWludF9maWVsZBgCIAEoBVIIaW50RmllbGQSHQoKYm9vbF9maWVsZBgDIAEoCFIJYm9vbEZpZWxkEh8KC2J5dGVzX2ZpZWxkGAQgASgMUgpieXRlc0ZpZWxkEhsKCWRibF9maWVsZBgFIAEoAVIIZGJsRmllbGQSHQoKbG9uZ19maWVsZBgGIAEoA1IJbG9uZ0ZpZWxkEjQKCmVudW1fZmllbGQYByABKA4yFS5maXh0dXJlcy5lMjAyMy5Db2xvclIJZW51bUZpZWxkEjMKCW1zZ19maWVsZBgIIAEoCzIWLmZpeHR1cmVzLmUyMDIzLk5lc3RlZFIIbXNnRmllbGQSEgoEdGFncxgJIAMoCVIEdGFncxIyCghjaGlsZHJlbhgKIAMoCzIWLmZpeHR1cmVzLmUyMDIzLk5lc3RlZFIIY2hpbGRyZW4SOwoGY291bnRzGAsgAygLMiMuZml4dHVyZXMuZTIwMjMuS2l0Y2hlbi5Db3VudHNFbnRyeVIGY291bnRzEh8KCmNob2ljZV9zdHIYDCABKAlIAFIJY2hvaWNlU3RyEh8KCmNob2ljZV9pbnQYDSABKAVIAFIJY2hvaWNlSW50EjcKCmNob2ljZV9tc2cYDiABKAsyFi5maXh0dXJlcy5lMjAyMy5OZXN0ZWRIAFIJY2hvaWNlTXNnEioKAnRzGA8gASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcFICdHMSKwoDZHVyGBAgASgLMhkuZ29vZ2xlLnByb3RvYnVmLkR1cmF0aW9uUgNkdXISNgoHd3JhcHBlZBgRIAEoCzIcLmdvb2dsZS5wcm90b2J1Zi5TdHJpbmdWYWx1ZVIHd3JhcHBlZBIsCg5pbXBsaWNpdF9maWVsZBgSIAEoCUIFqgECCAJSDWltcGxpY2l0RmllbGQSPgoJZGVsaW1pdGVkGBMgASgLMhkuZml4dHVyZXMuZTIwMjMuRGVsaW1pdGVkQgWqAQIoAlIJZGVsaW1pdGVkGjkKC0NvdW50c0VudHJ5EhAKA2tleRgBIAEoCVIDa2V5EhQKBXZhbHVlGAIgASgFUgV2YWx1ZToCOAFCCAoGY2hvaWNlIh8KCURlbGltaXRlZBISCgRub3RlGAEgASgJUgRub3RlKj0KBUNvbG9yEhUKEUNPTE9SX1VOU1BFQ0lGSUVEEAASDQoJQ09MT1JfUkVEEAESDgoKQ09MT1JfQkxVRRACQhsKF2NvbS5hY21lLmZpeHR1cmVzLmUyMDIzUAFiCGVkaXRpb25zcOgH")

(def file-descriptor
  (rt/file-descriptor descriptor-b64
                      [(rt/known-file "google/protobuf/duration.proto")
                       (rt/known-file "google/protobuf/timestamp.proto")
                       (rt/known-file "google/protobuf/wrappers.proto")]))

;; ---------------------------------------------------------------
;; messages
(declare Nested->proto Kitchen->proto Delimited->proto proto->Nested--map proto->Nested--slot-map proto->Delimited--slot-map)
;;
;; The shape is known at codegen time, so the representation is too:
;; a defrecord per type, its FieldDescriptors resolved once into
;; vars, and straight-line ->proto/proto-> built on them. nil means
;; absent, which is how a record (all keys always present) maps onto
;; protobuf explicit presence.

(defrecord Nested [id])
(def Nested-prototype (rt/message file-descriptor "Nested" "com.acme.fixtures.e2023.Nested"))
(def ^:private Nested--id (rt/field Nested-prototype "id"))
(defn Nested->proto
  "Clojure -> protobuf. Takes the Nested record or any map
  with the same keys — records and plain maps are interchangeable."
  ([m] (Nested->proto m nil))
  ([m opts]
   (if (nil? opts)
     (let [b (com.acme.fixtures.e2023.Nested/newBuilder)]
       (when-some [v (:id m)] (.setId b ^String v))
       (.build b))
     (let [b (.newBuilderForType ^com.google.protobuf.Message Nested-prototype)]
       (codec/set-field! b Nested--id (:id m) opts)
       (.build b)))))
(defn proto->Nested
  "protobuf -> a Nested record. Absent fields are nil."
  ([msg] (proto->Nested msg nil))
  ([^com.google.protobuf.Message msg opts]
   (cond
     (and (nil? opts) (instance? com.acme.fixtures.e2023.Nested msg))
     (let [^com.acme.fixtures.e2023.Nested m msg]
       (->Nested
        (when (.hasId m) (.getId m))
        ))

     (and (nil? opts) (rt/compiled-message? msg))
     (->Nested
      (rt/slot msg 0)
      )

     :else
     (->Nested
      (codec/get-field msg Nested--id opts)
      ))))
(defn- proto->Nested--map
  "Nested as the plain map a nested field reads back as:
  the same values, minus the keys the codec's read leaves out."
  [^com.acme.fixtures.e2023.Nested m]
  (let [id--v (when (.hasId m) (.getId m))]
    (if (some? id--v)
      {:id id--v}
      {})))
(defn- proto->Nested--slot-map
  "Nested as a plain map, read from the compiled arm's slots:
  the same values, minus the keys the codec's read leaves out."
  [msg]
  (let [id--v (rt/slot msg 0)]
    (if (some? id--v)
      {:id id--v}
      {})))

(defrecord Kitchen [str-field int-field bool-field bytes-field dbl-field long-field enum-field msg-field tags children counts choice-str choice-int choice-msg ts dur wrapped implicit-field delimited])
(def Kitchen-prototype (rt/message file-descriptor "Kitchen" "com.acme.fixtures.e2023.Kitchen"))
(def ^:private Kitchen--str-field (rt/field Kitchen-prototype "str_field"))
(def ^:private Kitchen--int-field (rt/field Kitchen-prototype "int_field"))
(def ^:private Kitchen--bool-field (rt/field Kitchen-prototype "bool_field"))
(def ^:private Kitchen--bytes-field (rt/field Kitchen-prototype "bytes_field"))
(def ^:private Kitchen--dbl-field (rt/field Kitchen-prototype "dbl_field"))
(def ^:private Kitchen--long-field (rt/field Kitchen-prototype "long_field"))
(def ^:private Kitchen--enum-field (rt/field Kitchen-prototype "enum_field"))
(def ^:private Kitchen--msg-field (rt/field Kitchen-prototype "msg_field"))
(def ^:private Kitchen--tags (rt/field Kitchen-prototype "tags"))
(def ^:private Kitchen--children (rt/field Kitchen-prototype "children"))
(def ^:private Kitchen--counts (rt/field Kitchen-prototype "counts"))
(def ^:private Kitchen--choice-str (rt/field Kitchen-prototype "choice_str"))
(def ^:private Kitchen--choice-int (rt/field Kitchen-prototype "choice_int"))
(def ^:private Kitchen--choice-msg (rt/field Kitchen-prototype "choice_msg"))
(def ^:private Kitchen--ts (rt/field Kitchen-prototype "ts"))
(def ^:private Kitchen--dur (rt/field Kitchen-prototype "dur"))
(def ^:private Kitchen--wrapped (rt/field Kitchen-prototype "wrapped"))
(def ^:private Kitchen--implicit-field (rt/field Kitchen-prototype "implicit_field"))
(def ^:private Kitchen--delimited (rt/field Kitchen-prototype "delimited"))
(defn Kitchen->proto
  "Clojure -> protobuf. Takes the Kitchen record or any map
  with the same keys — records and plain maps are interchangeable."
  ([m] (Kitchen->proto m nil))
  ([m opts]
   (if (nil? opts)
     (let [b (com.acme.fixtures.e2023.Kitchen/newBuilder)]
       (when-some [v (:str-field m)] (.setStrField b ^String v))
       (when-some [v (:int-field m)] (.setIntField b (int v)))
       (when-some [v (:bool-field m)] (.setBoolField b (boolean v)))
       (when-some [v (:bytes-field m)] (.setBytesField b (if (bytes? v) (com.google.protobuf.ByteString/copyFrom ^bytes v) ^com.google.protobuf.ByteString v)))
       (when-some [v (:dbl-field m)] (.setDblField b (double v)))
       (when-some [v (:long-field m)] (.setLongField b (long v)))
       (codec/set-field! b Kitchen--enum-field (:enum-field m) nil)
       (when-some [v (:msg-field m)] (if (map? v) (.setMsgField b ^com.acme.fixtures.e2023.Nested (Nested->proto v nil)) (codec/set-field! b Kitchen--msg-field v nil)))
       (codec/set-field! b Kitchen--tags (:tags m) nil)
       (codec/set-field! b Kitchen--children (:children m) nil)
       (codec/set-field! b Kitchen--counts (:counts m) nil)
       (when-some [v (:choice-str m)] (.setChoiceStr b ^String v))
       (when-some [v (:choice-int m)] (.setChoiceInt b (int v)))
       (when-some [v (:choice-msg m)] (if (map? v) (.setChoiceMsg b ^com.acme.fixtures.e2023.Nested (Nested->proto v nil)) (codec/set-field! b Kitchen--choice-msg v nil)))
       (codec/set-field! b Kitchen--ts (:ts m) nil)
       (codec/set-field! b Kitchen--dur (:dur m) nil)
       (codec/set-field! b Kitchen--wrapped (:wrapped m) nil)
       (when-some [v (:implicit-field m)] (.setImplicitField b ^String v))
       (when-some [v (:delimited m)] (if (map? v) (.setDelimited b ^com.acme.fixtures.e2023.Delimited (Delimited->proto v nil)) (codec/set-field! b Kitchen--delimited v nil)))
       (.build b))
     (let [b (.newBuilderForType ^com.google.protobuf.Message Kitchen-prototype)]
       (codec/set-field! b Kitchen--str-field (:str-field m) opts)
       (codec/set-field! b Kitchen--int-field (:int-field m) opts)
       (codec/set-field! b Kitchen--bool-field (:bool-field m) opts)
       (codec/set-field! b Kitchen--bytes-field (:bytes-field m) opts)
       (codec/set-field! b Kitchen--dbl-field (:dbl-field m) opts)
       (codec/set-field! b Kitchen--long-field (:long-field m) opts)
       (codec/set-field! b Kitchen--enum-field (:enum-field m) opts)
       (codec/set-field! b Kitchen--msg-field (:msg-field m) opts)
       (codec/set-field! b Kitchen--tags (:tags m) opts)
       (codec/set-field! b Kitchen--children (:children m) opts)
       (codec/set-field! b Kitchen--counts (:counts m) opts)
       (codec/set-field! b Kitchen--choice-str (:choice-str m) opts)
       (codec/set-field! b Kitchen--choice-int (:choice-int m) opts)
       (codec/set-field! b Kitchen--choice-msg (:choice-msg m) opts)
       (codec/set-field! b Kitchen--ts (:ts m) opts)
       (codec/set-field! b Kitchen--dur (:dur m) opts)
       (codec/set-field! b Kitchen--wrapped (:wrapped m) opts)
       (codec/set-field! b Kitchen--implicit-field (:implicit-field m) opts)
       (codec/set-field! b Kitchen--delimited (:delimited m) opts)
       (.build b)))))
(defn proto->Kitchen
  "protobuf -> a Kitchen record. Absent fields are nil."
  ([msg] (proto->Kitchen msg nil))
  ([^com.google.protobuf.Message msg opts]
   (cond
     (and (nil? opts) (instance? com.acme.fixtures.e2023.Kitchen msg))
     (let [^com.acme.fixtures.e2023.Kitchen m msg]
       (->Kitchen
        (when (.hasStrField m) (.getStrField m))
        (when (.hasIntField m) (.getIntField m))
        (when (.hasBoolField m) (.getBoolField m))
        (when (.hasBytesField m) (.toByteArray (.getBytesField m)))
        (when (.hasDblField m) (.getDblField m))
        (when (.hasLongField m) (.getLongField m))
        (when (.hasEnumField m) (case (.getEnumFieldValue m) 0 :COLOR_UNSPECIFIED 1 :COLOR_RED 2 :COLOR_BLUE (codec/get-field m Kitchen--enum-field nil)))
        (when (.hasMsgField m) (proto->Nested--map (.getMsgField m)))
        (let [l (.getTagsList m)] (when-not (.isEmpty l) (vec l)))
        (let [l (.getChildrenList m)] (when-not (.isEmpty l) (persistent! (reduce (fn [acc v] (conj! acc (proto->Nested--map v))) (transient []) l))))
        (let [jm (.getCountsMap m)] (when-not (.isEmpty jm) (persistent! (reduce (fn [acc ^java.util.Map$Entry e] (assoc! acc (.getKey e) (.getValue e))) (transient {}) (.entrySet jm)))))
        (when (.hasChoiceStr m) (.getChoiceStr m))
        (when (.hasChoiceInt m) (.getChoiceInt m))
        (when (.hasChoiceMsg m) (proto->Nested--map (.getChoiceMsg m)))
        (codec/get-field m Kitchen--ts nil)
        (codec/get-field m Kitchen--dur nil)
        (codec/get-field m Kitchen--wrapped nil)
        (.getImplicitField m)
        (codec/get-field m Kitchen--delimited nil)
        ))

     (and (nil? opts) (rt/compiled-message? msg))
     (->Kitchen
      (rt/slot msg 0)
      (rt/slot msg 1)
      (rt/slot msg 2)
      (when-some [v (rt/slot msg 3)] (.toByteArray ^com.google.protobuf.ByteString v))
      (rt/slot msg 4)
      (rt/slot msg 5)
      (when-some [v (rt/slot msg 6)] (case v 0 :COLOR_UNSPECIFIED 1 :COLOR_RED 2 :COLOR_BLUE (codec/get-field msg Kitchen--enum-field nil)))
      (when-some [v (rt/slot msg 7)] (proto->Nested--slot-map v))
      (let [^java.util.List l (rt/slot msg 8)] (when (and l (pos? (.size l))) (vec l)))
      (let [^java.util.List l (rt/slot msg 9)] (when (and l (pos? (.size l))) (persistent! (reduce (fn [acc v] (conj! acc (proto->Nested--slot-map v))) (transient []) l))))
      (let [^java.util.Map jm (rt/slot msg 10)] (when (and jm (pos? (.size jm))) (persistent! (reduce (fn [acc ^java.util.Map$Entry e] (assoc! acc (.getKey e) (.getValue e))) (transient {}) (.entrySet jm)))))
      (rt/slot msg 11)
      (rt/slot msg 12)
      (when-some [v (rt/slot msg 13)] (proto->Nested--slot-map v))
      (codec/get-field msg Kitchen--ts nil)
      (codec/get-field msg Kitchen--dur nil)
      (codec/get-field msg Kitchen--wrapped nil)
      (let [v (rt/slot msg 17)] (if (nil? v) "" v))
      (when-some [v (rt/slot msg 18)] (proto->Delimited--slot-map v))
      )

     :else
     (->Kitchen
      (codec/get-field msg Kitchen--str-field opts)
      (codec/get-field msg Kitchen--int-field opts)
      (codec/get-field msg Kitchen--bool-field opts)
      (codec/get-field msg Kitchen--bytes-field opts)
      (codec/get-field msg Kitchen--dbl-field opts)
      (codec/get-field msg Kitchen--long-field opts)
      (codec/get-field msg Kitchen--enum-field opts)
      (codec/get-field msg Kitchen--msg-field opts)
      (codec/get-field msg Kitchen--tags opts)
      (codec/get-field msg Kitchen--children opts)
      (codec/get-field msg Kitchen--counts opts)
      (codec/get-field msg Kitchen--choice-str opts)
      (codec/get-field msg Kitchen--choice-int opts)
      (codec/get-field msg Kitchen--choice-msg opts)
      (codec/get-field msg Kitchen--ts opts)
      (codec/get-field msg Kitchen--dur opts)
      (codec/get-field msg Kitchen--wrapped opts)
      (codec/get-field msg Kitchen--implicit-field opts)
      (codec/get-field msg Kitchen--delimited opts)
      ))))

(defrecord Delimited [note])
(def Delimited-prototype (rt/message file-descriptor "Delimited" "com.acme.fixtures.e2023.Delimited"))
(def ^:private Delimited--note (rt/field Delimited-prototype "note"))
(defn Delimited->proto
  "Clojure -> protobuf. Takes the Delimited record or any map
  with the same keys — records and plain maps are interchangeable."
  ([m] (Delimited->proto m nil))
  ([m opts]
   (if (nil? opts)
     (let [b (com.acme.fixtures.e2023.Delimited/newBuilder)]
       (when-some [v (:note m)] (.setNote b ^String v))
       (.build b))
     (let [b (.newBuilderForType ^com.google.protobuf.Message Delimited-prototype)]
       (codec/set-field! b Delimited--note (:note m) opts)
       (.build b)))))
(defn proto->Delimited
  "protobuf -> a Delimited record. Absent fields are nil."
  ([msg] (proto->Delimited msg nil))
  ([^com.google.protobuf.Message msg opts]
   (cond
     (and (nil? opts) (instance? com.acme.fixtures.e2023.Delimited msg))
     (let [^com.acme.fixtures.e2023.Delimited m msg]
       (->Delimited
        (when (.hasNote m) (.getNote m))
        ))

     (and (nil? opts) (rt/compiled-message? msg))
     (->Delimited
      (rt/slot msg 0)
      )

     :else
     (->Delimited
      (codec/get-field msg Delimited--note opts)
      ))))
(defn- proto->Delimited--slot-map
  "Delimited as a plain map, read from the compiled arm's slots:
  the same values, minus the keys the codec's read leaves out."
  [msg]
  (let [note--v (rt/slot msg 0)]
    (if (some? note--v)
      {:note note--v}
      {})))
