;; Generated by protoc-gen-clojure from fixtures/e2024/kitchen.proto. Do not edit.
;;
;; The FileDescriptorProto below is embedded verbatim; protobuf-java resolves
;; its edition features at load time, so this file needs no regeneration when
;; a new edition ships.
(ns fixtures.e2024.kitchen
  (:require [clj-grpc.codec :as codec]
            [clj-grpc.runtime :as rt]))

(def ^:private descriptor-b64
  "ChxmaXh0dXJlcy9lMjAyNC9raXRjaGVuLnByb3RvEg5maXh0dXJlcy5lMjAyNBoeZ29vZ2xlL3Byb3RvYnVmL2R1cmF0aW9uLnByb3RvGh9nb29nbGUvcHJvdG9idWYvdGltZXN0YW1wLnByb3RvGh5nb29nbGUvcHJvdG9idWYvd3JhcHBlcnMucHJvdG8iGAoGTmVzdGVkEg4KAmlkGAEgASgJUgJpZCIfCglEZWxpbWl0ZWQSEgoEbm90ZRgBIAEoCVIEbm90ZSLuBgoHS2l0Y2hlbhIbCglzdHJfZmllbGQYASABKAlSCHN0ckZpZWxkEhsKCWludF9maWVsZBgCIAEoBVIIaW50RmllbGQSHQoKYm9vbF9maWVsZBgDIAEoCFIJYm9vbEZpZWxkEh8KC2J5dGVzX2ZpZWxkGAQgASgMUgpieXRlc0ZpZWxkEhsKCWRibF9maWVsZBgFIAEoAVIIZGJsRmllbGQSHQoKbG9uZ19maWVsZBgGIAEoA1IJbG9uZ0ZpZWxkEjQKCmVudW1fZmllbGQYByABKA4yFS5maXh0dXJlcy5lMjAyNC5Db2xvclIJZW51bUZpZWxkEjMKCW1zZ19maWVsZBgIIAEoCzIWLmZpeHR1cmVzLmUyMDI0Lk5lc3RlZFIIbXNnRmllbGQSEgoEdGFncxgJIAMoCVIEdGFncxIyCghjaGlsZHJlbhgKIAMoCzIWLmZpeHR1cmVzLmUyMDI0Lk5lc3RlZFIIY2hpbGRyZW4SOwoGY291bnRzGAsgAygLMiMuZml4dHVyZXMuZTIwMjQuS2l0Y2hlbi5Db3VudHNFbnRyeVIGY291bnRzEh8KCmNob2ljZV9zdHIYDCABKAlIAFIJY2hvaWNlU3RyEh8KCmNob2ljZV9pbnQYDSABKAVIAFIJY2hvaWNlSW50EjcKCmNob2ljZV9tc2cYDiABKAsyFi5maXh0dXJlcy5lMjAyNC5OZXN0ZWRIAFIJY2hvaWNlTXNnEioKAnRzGA8gASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcFICdHMSKwoDZHVyGBAgASgLMhkuZ29vZ2xlLnByb3RvYnVmLkR1cmF0aW9uUgNkdXISNgoHd3JhcHBlZBgRIAEoCzIcLmdvb2dsZS5wcm90b2J1Zi5TdHJpbmdWYWx1ZVIHd3JhcHBlZBIsCg5pbXBsaWNpdF9maWVsZBgSIAEoCUIFqgECCAJSDWltcGxpY2l0RmllbGQSPgoJZGVsaW1pdGVkGBMgASgLMhkuZml4dHVyZXMuZTIwMjQuRGVsaW1pdGVkQgWqAQIoAlIJZGVsaW1pdGVkGjkKC0NvdW50c0VudHJ5EhAKA2tleRgBIAEoCVIDa2V5EhQKBXZhbHVlGAIgASgFUgV2YWx1ZToCOAFCCAoGY2hvaWNlIiwKEU5lc3RlZEluRmlsZUNsYXNzEg4KAmlkGAEgASgJUgJpZDoHYgXKPgIoAio9CgVDb2xvchIVChFDT0xPUl9VTlNQRUNJRklFRBAAEg0KCUNPTE9SX1JFRBABEg4KCkNPTE9SX0JMVUUQAkIZChdjb20uYWNtZS5maXh0dXJlcy5lMjAyNGIIZWRpdGlvbnNw6Qd6I2dvb2dsZS9wcm90b2J1Zi9qYXZhX2ZlYXR1cmVzLnByb3Rv")

(def file-descriptor
  (rt/file-descriptor descriptor-b64
                      [(rt/known-file "google/protobuf/duration.proto")
                       (rt/known-file "google/protobuf/timestamp.proto")
                       (rt/known-file "google/protobuf/wrappers.proto")]))

;; ---------------------------------------------------------------
;; messages
;;
;; The shape is known at codegen time, so the representation is too:
;; a defrecord per type, its FieldDescriptors resolved once into
;; vars, and straight-line ->proto/proto-> built on them. nil means
;; absent, which is how a record (all keys always present) maps onto
;; protobuf explicit presence.

(defrecord Nested [id])
(def Nested-prototype (rt/message file-descriptor "Nested"))
(def ^:private Nested--id (rt/field Nested-prototype "id"))
(defn Nested->proto
  "Clojure -> protobuf. Takes the Nested record or any map
  with the same keys — records and plain maps are interchangeable."
  ([m] (Nested->proto m nil))
  ([m opts]
   (let [b (.newBuilderForType ^com.google.protobuf.Message Nested-prototype)]
     (codec/set-field! b Nested--id (:id m) opts)
     (.build b))))
(defn proto->Nested
  "protobuf -> a Nested record. Absent fields are nil."
  ([msg] (proto->Nested msg nil))
  ([^com.google.protobuf.Message msg opts]
   (->Nested
    (codec/get-field msg Nested--id opts)
    )))

(defrecord Delimited [note])
(def Delimited-prototype (rt/message file-descriptor "Delimited"))
(def ^:private Delimited--note (rt/field Delimited-prototype "note"))
(defn Delimited->proto
  "Clojure -> protobuf. Takes the Delimited record or any map
  with the same keys — records and plain maps are interchangeable."
  ([m] (Delimited->proto m nil))
  ([m opts]
   (let [b (.newBuilderForType ^com.google.protobuf.Message Delimited-prototype)]
     (codec/set-field! b Delimited--note (:note m) opts)
     (.build b))))
(defn proto->Delimited
  "protobuf -> a Delimited record. Absent fields are nil."
  ([msg] (proto->Delimited msg nil))
  ([^com.google.protobuf.Message msg opts]
   (->Delimited
    (codec/get-field msg Delimited--note opts)
    )))

(defrecord Kitchen [str-field int-field bool-field bytes-field dbl-field long-field enum-field msg-field tags children counts choice-str choice-int choice-msg ts dur wrapped implicit-field delimited])
(def Kitchen-prototype (rt/message file-descriptor "Kitchen"))
(def ^:private Kitchen--str-field (rt/field Kitchen-prototype "str_field"))
(def ^:private Kitchen--int-field (rt/field Kitchen-prototype "int_field"))
(def ^:private Kitchen--bool-field (rt/field Kitchen-prototype "bool_field"))
(def ^:private Kitchen--bytes-field (rt/field Kitchen-prototype "bytes_field"))
(def ^:private Kitchen--dbl-field (rt/field Kitchen-prototype "dbl_field"))
(def ^:private Kitchen--long-field (rt/field Kitchen-prototype "long_field"))
(def ^:private Kitchen--enum-field (rt/field Kitchen-prototype "enum_field"))
(def ^:private Kitchen--msg-field (rt/field Kitchen-prototype "msg_field"))
(def ^:private Kitchen--tags (rt/field Kitchen-prototype "tags"))
(def ^:private Kitchen--children (rt/field Kitchen-prototype "children"))
(def ^:private Kitchen--counts (rt/field Kitchen-prototype "counts"))
(def ^:private Kitchen--choice-str (rt/field Kitchen-prototype "choice_str"))
(def ^:private Kitchen--choice-int (rt/field Kitchen-prototype "choice_int"))
(def ^:private Kitchen--choice-msg (rt/field Kitchen-prototype "choice_msg"))
(def ^:private Kitchen--ts (rt/field Kitchen-prototype "ts"))
(def ^:private Kitchen--dur (rt/field Kitchen-prototype "dur"))
(def ^:private Kitchen--wrapped (rt/field Kitchen-prototype "wrapped"))
(def ^:private Kitchen--implicit-field (rt/field Kitchen-prototype "implicit_field"))
(def ^:private Kitchen--delimited (rt/field Kitchen-prototype "delimited"))
(defn Kitchen->proto
  "Clojure -> protobuf. Takes the Kitchen record or any map
  with the same keys — records and plain maps are interchangeable."
  ([m] (Kitchen->proto m nil))
  ([m opts]
   (let [b (.newBuilderForType ^com.google.protobuf.Message Kitchen-prototype)]
     (codec/set-field! b Kitchen--str-field (:str-field m) opts)
     (codec/set-field! b Kitchen--int-field (:int-field m) opts)
     (codec/set-field! b Kitchen--bool-field (:bool-field m) opts)
     (codec/set-field! b Kitchen--bytes-field (:bytes-field m) opts)
     (codec/set-field! b Kitchen--dbl-field (:dbl-field m) opts)
     (codec/set-field! b Kitchen--long-field (:long-field m) opts)
     (codec/set-field! b Kitchen--enum-field (:enum-field m) opts)
     (codec/set-field! b Kitchen--msg-field (:msg-field m) opts)
     (codec/set-field! b Kitchen--tags (:tags m) opts)
     (codec/set-field! b Kitchen--children (:children m) opts)
     (codec/set-field! b Kitchen--counts (:counts m) opts)
     (codec/set-field! b Kitchen--choice-str (:choice-str m) opts)
     (codec/set-field! b Kitchen--choice-int (:choice-int m) opts)
     (codec/set-field! b Kitchen--choice-msg (:choice-msg m) opts)
     (codec/set-field! b Kitchen--ts (:ts m) opts)
     (codec/set-field! b Kitchen--dur (:dur m) opts)
     (codec/set-field! b Kitchen--wrapped (:wrapped m) opts)
     (codec/set-field! b Kitchen--implicit-field (:implicit-field m) opts)
     (codec/set-field! b Kitchen--delimited (:delimited m) opts)
     (.build b))))
(defn proto->Kitchen
  "protobuf -> a Kitchen record. Absent fields are nil."
  ([msg] (proto->Kitchen msg nil))
  ([^com.google.protobuf.Message msg opts]
   (->Kitchen
    (codec/get-field msg Kitchen--str-field opts)
    (codec/get-field msg Kitchen--int-field opts)
    (codec/get-field msg Kitchen--bool-field opts)
    (codec/get-field msg Kitchen--bytes-field opts)
    (codec/get-field msg Kitchen--dbl-field opts)
    (codec/get-field msg Kitchen--long-field opts)
    (codec/get-field msg Kitchen--enum-field opts)
    (codec/get-field msg Kitchen--msg-field opts)
    (codec/get-field msg Kitchen--tags opts)
    (codec/get-field msg Kitchen--children opts)
    (codec/get-field msg Kitchen--counts opts)
    (codec/get-field msg Kitchen--choice-str opts)
    (codec/get-field msg Kitchen--choice-int opts)
    (codec/get-field msg Kitchen--choice-msg opts)
    (codec/get-field msg Kitchen--ts opts)
    (codec/get-field msg Kitchen--dur opts)
    (codec/get-field msg Kitchen--wrapped opts)
    (codec/get-field msg Kitchen--implicit-field opts)
    (codec/get-field msg Kitchen--delimited opts)
    )))

(defrecord NestedInFileClass [id])
(def NestedInFileClass-prototype (rt/message file-descriptor "NestedInFileClass"))
(def ^:private NestedInFileClass--id (rt/field NestedInFileClass-prototype "id"))
(defn NestedInFileClass->proto
  "Clojure -> protobuf. Takes the NestedInFileClass record or any map
  with the same keys — records and plain maps are interchangeable."
  ([m] (NestedInFileClass->proto m nil))
  ([m opts]
   (let [b (.newBuilderForType ^com.google.protobuf.Message NestedInFileClass-prototype)]
     (codec/set-field! b NestedInFileClass--id (:id m) opts)
     (.build b))))
(defn proto->NestedInFileClass
  "protobuf -> a NestedInFileClass record. Absent fields are nil."
  ([msg] (proto->NestedInFileClass msg nil))
  ([^com.google.protobuf.Message msg opts]
   (->NestedInFileClass
    (codec/get-field msg NestedInFileClass--id opts)
    )))
